name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 19.1.0
      - name: Install Dependencies
        run: 
          npm install
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          install: false
          command:  npx cypress run || npm run posttest
        env:
          CYPRESS_host: api.dev.local
          CYPRESS_port: 4222
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/assets/reports/screenshots
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: cypress/assets/reports/videos
